# Reference http://www.appveyor.com/docs/appveyor-yml
version: '{build}'
os: Visual Studio 2015

environment:
  matrix:
  - VCINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
    QTDIR: C:\Qt\5.7\msvc2015_64
  gh_token:
    secure: mQh8gJ+nWvz2ZEQ3kZEAEM1pXw+U4mnvp8rhqam/VyNB+ckzVX4GK1PZfnm58rpm

configuration:
- Release

matrix:
  fast_finish: true

install:
  - cd %REPO_DIR%
  - git submodule update --init --recursive

before_build:
  - set PATH=%PATH%;%QTDIR%\bin
  - CALL "%VCINSTALLDIR%\vcvarsall.bat" amd64
# zlib
  - cd %APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ../
  - msbuild /nologo /t:Build /p:Configuration=Debug zlib.sln
  - msbuild /nologo /t:Build /p:Configuration=Release zlib.sln
# quazip
  - cd %APPVEYOR_BUILD_FOLDER%\ThirdParty\quazip
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DZLIB_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib;%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib\build" -DZLIB_LIBRARY="%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib\build\Debug\zlibd.lib" ../
  - msbuild /nologo /t:Build /p:Configuration=Debug quazip.sln
  - cmake -G "Visual Studio 14 2015 Win64" -DZLIB_INCLUDE_DIR="%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib;%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib\build" -DZLIB_LIBRARY="%APPVEYOR_BUILD_FOLDER%\ThirdParty\zlib\build\Release\zlib.lib" ../
  - msbuild /nologo /t:Build /p:Configuration=Release quazip.sln

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - qmake eshare.pro -config release -spec win32-msvc2015
  - nmake BUILD=release

after_build:
  - cd %REPO_DIR%
  - git rev-parse --verify HEAD > %APPVEYOR_BUILD_FOLDER%\trigger
  - cd %APPVEYOR_BUILD_FOLDER%
  - mkdir eshare
  - copy release\eshare.exe eshare
  - copy ThirdParty\zlib\build\Release\zlib.dll eshare
  - copy ThirdParty\quazip\build\Release\quazip.dll eshare
  - copy "%VCINSTALLDIR%\redist\x64\Microsoft.VC140.CRT\msvcp140.dll" eshare
  - copy "%VCINSTALLDIR%\redist\x64\Microsoft.VC140.CRT\vcruntime140.dll" eshare
  - copy "%QTDIR%\bin\Qt5Core.dll" eshare
  - copy "%QTDIR%\bin\Qt5Gui.dll" eshare
  - copy "%QTDIR%\bin\Qt5Network.dll" eshare
  - copy "%QTDIR%\bin\Qt5Widgets.dll" eshare
  - mkdir eshare\platforms
  - copy "%QTDIR%\plugins\platforms\qwindows.dll" eshare\platforms
  - copy trigger eshare
  - 7z a -tzip -mx9 eshare.zip eshare

artifacts:
  - path: eshare.zip
    name: eshare-archive

# Tags aren't updated by appveyor, use a powershell script to do a "latest build overwrite" deployment
before_deploy:
  - git config --global user.name "Marco A."
  - git config --global user.email "marcodiiga@users.noreply.github.com"
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:gh_token):x-oauth-basic@github.com`n"
  - git remote set-url origin https://github.com/marcodiiga/eshare.git
  - git tag -d eshare         # Delete existing tag - this may fail, failure should be ignored
  - git tag eshare HEAD       # Create new tag mytag matching latest commit
  - git push -f origin eshare # Push mytag to GitHub, overwriting existing tag

deploy:
  release: eshare
  description: '[Win64 Release] eshare packed archive (portable)'
  provider: GitHub
  auth_token:
    secure: mQh8gJ+nWvz2ZEQ3kZEAEM1pXw+U4mnvp8rhqam/VyNB+ckzVX4GK1PZfnm58rpm
  artifact: eshare-archive
  draft: false
  prerelease: false
  force_update: true # Overwrite existing releases
  on:
    branch: master # Release from master branch only
